version: "3"


services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db


volumes:
  redis:
  redisinsight: